package features;

/**
 * Created by 50021824 on 17-07-2017.
 */
  import java.util.Properties;

  import javax.activation.DataHandler;
  import javax.activation.DataSource;
  import javax.activation.FileDataSource;
  import javax.mail.*;
  import javax.mail.internet.InternetAddress;
  import javax.mail.internet.MimeBodyPart;
  import javax.mail.internet.MimeMessage;
  import javax.mail.internet.MimeMultipart;

public class SendMailTLS {

        public static void main(String[] args) {

            final String username = "bharath.gajulapalli@conduent.com";
            final String password = "Jun@2017";

            Properties props = new Properties();
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.host", "smtp.office365.com");
            props.put("mail.smtp.port", "587");

            Session session = Session.getInstance(props,
                    new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });

            try {

                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress("bharath.gajulapalli@conduent.com"));
                message.setRecipients(Message.RecipientType.TO,
                        InternetAddress.parse("bharath.gajulapalli@conduent.com"));
                message.setSubject("Florida Tolling Automation Test Execution Report");



                BodyPart messageBodyPart = new MimeBodyPart();
                messageBodyPart.setText("Hi team ,"
                        + "\n\n Please find the attachment for Test Execution Report \n  This is autoGenerated Test Execution Report \n\n\n Please Dont Reply to this mail!"

                        + "Regards \n Bharath Kumar G " );

                // Now set the actual message
                //messageBodyPart.setText("Hi Team, \n Please find the automation status as an attachment \n\n Thanks \n " );

                // Create a multipar message
                Multipart multipart = new MimeMultipart();

                // Set text message part
                multipart.addBodyPart(messageBodyPart);

                // Part two is attachment
                messageBodyPart = new MimeBodyPart();
                String filename = System.getProperty("user.dir").concat("/testfile.html");
                System.out.println(filename);
               // String filename = "testfile.html";
                DataSource source = new FileDataSource(filename);
                messageBodyPart.setDataHandler(new DataHandler(source));
                messageBodyPart.setFileName(filename);
                multipart.addBodyPart(messageBodyPart);
                message.setContent(multipart);

                Transport.send(message);

                System.out.println("Done");

            } catch (MessagingException e) {
                throw new RuntimeException(e);
            }
        }
    }
